### ISSUE TITLE
使用无效

### ISSUE THREAD

**Issue by Faker-ZhangSan** [tianxiatianshan/AndroidLanguageSwitch#1]
想请教一下   使用demo写或创建新的项目是ok的  在现有的项目中是无法生效的  打断点和这个项目显示是一样的  请问一下有可能是什么原因导致的

**Comment by tianxiatianshan** [comment]
能描述下具体怎么使用的吗；  可以加 QQ： 1444672626

**Comment by Faker-ZhangSan** [comment]
因为bulid文件设置了固定的文件类型导致的&nbsp; 已经解决了&nbsp; 谢谢回复&nbsp; 库很好用&nbsp; 很方便



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月16日(周五) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tianxiatianshan/AndroidLanguageSwitch] 使用无效 (#1)




 
能描述下具体怎么使用的吗；  可以加 QQ： 1444672626
